### PR TITLE
Fixed various import errors.

### PR DESCRIPTION
**Pull request by bradylangdale**
Now running on Ubuntu 20.04

### CODE REVIEW

**Comment by rfjohnso** [comment]
Thanks for the updates. I wasn't aware that things stopped working in later versions.  I need to get all my gear setup again and will test and then merge.

**Review by bradylangdale — COMMENTED** [review]
Removed sudo, I realized this was unnecessary.

**Comment by bradylangdale** [comment]
No problem! It was just minor PyQt5 stuff and PyAPRiL related imports.

**Comment by rfjohnso** [comment]
Ok, oops, I was trying to test the changes and I inadvertently merged the pr when I thought I was only doing it locally. I have having some issues getting it to work on my end now. Can you re-download and run this branch and see if it still works for you? The error I am getting is a numpy error from hydra_processing.py line 161 and is saying: ValueError: Buffer is smaller than requested size

**Pull request merged**
